     plugin query "filter-a-cond.so" {
       filter-a-on-v6 yes;
       filter-a-on-v4 yes;
       filter-a { any; };
       only-for-domains { "youtube.com."; "accounts.youtube.com"; "i.ytimg.com."; "wide-youtube.l.google.com."; "www3.l.google.com."; "clients.l.google.com."; "yt3.googleusercontent.com."; "googlevideo.com."; "accounts.google.com."; "doubleclick.net"; "youtube-ui.l.google.com.";};
    };

    plugin query "filter-aaaa-cond.so" {
       filter-aaaa-on-v6 yes;
       filter-aaaa-on-v4 yes;
       filter-aaaa { any; };
       only-for-domains_exact { "www.google.com."; };
    };
